<?php

declare(strict_types=1);

namespace Noxlogic\Oprf;

use Noxlogic\Oprf\Exception\OprfException;
use Noxlogic\Oprf\Group\GroupInterface;
use Noxlogic\Oprf\Group\Ristretto255Group;

/**
 * Server side of the OPRF protocol (RFC 9497, base mode).
 */
class OprfServer
{
    public function __construct(
        private readonly GroupInterface $group = new Ristretto255Group(),
    ) {}

    /**
     * Generate a new random server private key.
     *
     * @return string 32-byte scalar — store this securely; it is the OPRF key.
     */
    public function generateKey(): string
    {
        return $this->group->randomScalar();
    }

    /**
     * Evaluate a blinded element under the server key.
     *
     * @param string $privateKey     32-byte scalar generated by generateKey().
     * @param string $blindedElement 32-byte element received from the client.
     * @return string                32-byte evaluated element to return to the client.
     * @throws OprfException
     */
    public function evaluate(string $privateKey, string $blindedElement): string
    {
        if (!$this->group->isValidElement($blindedElement)) {
            throw new OprfException('Invalid blinded element received from client.');
        }

        return $this->group->scalarMult($privateKey, $blindedElement);
    }
}
